name: Terraform Apply
on:
  push:
    branches:
      - main
env:
  TF_VAR_DO_TOKEN: "${{ secrets.TF_VAR_DO_TOKEN }}"
  TF_VAR_CERT_NAME: "${{ secrets.TF_VAR_CERT_NAME }}"
  TF_VAR_DOMAIN: "${{ secrets.TF_VAR_DOMAIN }}"
  TF_VAR_CODER_VERSION: "${{ vars.TF_VAR_CODER_VERSION }}"
jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Init Configuration
        run: terraform init
      - name: Validate Configuration
        run: terraform validate
      - name: Plan Configuration
        run: TF_CLI_ARGS="-out=tfplan -input=false -refresh-only" terraform plan
#      - name: Apply Configuration
#        run: terraform apply
